name: fermipy

channels:
  - conda-forge
  - fermi
  - conda-forge/label/cf201901

dependencies:
  - python=2.7.18
  - fermitools=1.2.23
  - fermipy=0.20.0
#  - scipy
#  - matplotlib
#  - pyyaml
#  - numpy
#  - astropy
#  - gammapy
#  - healpy
