{% set name = "fermitools-build-deps" %}

package:
  name: {{ name|lower }}
  version: {{ environ.get('VERSION', 0)}}

# source:
#   git_url: https://github.com/fermi-lat/Fermitools-build-deps.git

build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}

requirements:
  run:
    - ape 3.0.*
    - aplpy 1.1.*
    - astropy 2.0.9.*
    - blas 2.17.*
    - clhep 2.4.1.*
    - cppunit 1.15.1.*
    - f2c 0.0.2.*
    - fermi-repoman 0.2.8.*
    - fftw 3.3.8.*
    - git 2.28.*
    - gsl 2.6.*
    - healpix_cxx 3.31.*
    - matplotlib 2.2.5.*
    - numpy 1.16.*
    - pmw 2.0.*
    - python 2.7.*
    - root 6.22.0.*
    - scipy 1.2.1.*
    - scons 3.1.2.*
    - swig 4.0.2.*
    - wcslib 5.20.*
    - xerces-c 3.2.3.*
    
